// <auto-generated/>
#pragma warning disable CS0618
using AEL.Core.Docling.Gamma.Models;
using AEL.Core.Docling.Gamma.V1.Chunk.Hierarchical.Source.Async;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace AEL.Core.Docling.Gamma.V1.Chunk.Hierarchical.Source
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\chunk\hierarchical\source
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SourceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The async property</summary>
        public global::AEL.Core.Docling.Gamma.V1.Chunk.Hierarchical.Source.Async.AsyncRequestBuilder Async
        {
            get => new global::AEL.Core.Docling.Gamma.V1.Chunk.Hierarchical.Source.Async.AsyncRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AEL.Core.Docling.Gamma.V1.Chunk.Hierarchical.Source.SourceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SourceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/chunk/hierarchical/source", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AEL.Core.Docling.Gamma.V1.Chunk.Hierarchical.Source.SourceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SourceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/chunk/hierarchical/source", rawUrl)
        {
        }
        /// <summary>
        /// Chunk Sources With Hierarchicalchunker
        /// </summary>
        /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.ChunkDocumentResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::AEL.Core.Docling.Gamma.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::AEL.Core.Docling.Gamma.Models.ChunkDocumentResponse?> PostAsync(global::AEL.Core.Docling.Gamma.Models.HierarchicalChunkerOptionsDocumentsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::AEL.Core.Docling.Gamma.Models.ChunkDocumentResponse> PostAsync(global::AEL.Core.Docling.Gamma.Models.HierarchicalChunkerOptionsDocumentsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::AEL.Core.Docling.Gamma.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::AEL.Core.Docling.Gamma.Models.ChunkDocumentResponse>(requestInfo, global::AEL.Core.Docling.Gamma.Models.ChunkDocumentResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Chunk Sources With Hierarchicalchunker
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::AEL.Core.Docling.Gamma.Models.HierarchicalChunkerOptionsDocumentsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::AEL.Core.Docling.Gamma.Models.HierarchicalChunkerOptionsDocumentsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.V1.Chunk.Hierarchical.Source.SourceRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::AEL.Core.Docling.Gamma.V1.Chunk.Hierarchical.Source.SourceRequestBuilder WithUrl(string rawUrl)
        {
            return new global::AEL.Core.Docling.Gamma.V1.Chunk.Hierarchical.Source.SourceRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
