// <auto-generated/>
#pragma warning disable CS0618
using AEL.Core.Docling.Gamma.Models;
using AEL.Core.Docling.Gamma.V1.ConvertNamespace.FileNamespace.Async;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace AEL.Core.Docling.Gamma.V1.ConvertNamespace.FileNamespace
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\convert\file
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FileRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The async property</summary>
        public global::AEL.Core.Docling.Gamma.V1.ConvertNamespace.FileNamespace.Async.AsyncRequestBuilder Async
        {
            get => new global::AEL.Core.Docling.Gamma.V1.ConvertNamespace.FileNamespace.Async.AsyncRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AEL.Core.Docling.Gamma.V1.ConvertNamespace.FileNamespace.FileRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FileRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/convert/file", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AEL.Core.Docling.Gamma.V1.ConvertNamespace.FileNamespace.FileRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FileRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/convert/file", rawUrl)
        {
        }
        /// <summary>
        /// Process File
        /// </summary>
        /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.V1.ConvertNamespace.FileNamespace.FileRequestBuilder.FilePostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::AEL.Core.Docling.Gamma.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::AEL.Core.Docling.Gamma.V1.ConvertNamespace.FileNamespace.FileRequestBuilder.FilePostResponse?> PostAsync(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::AEL.Core.Docling.Gamma.V1.ConvertNamespace.FileNamespace.FileRequestBuilder.FilePostResponse> PostAsync(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::AEL.Core.Docling.Gamma.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::AEL.Core.Docling.Gamma.V1.ConvertNamespace.FileNamespace.FileRequestBuilder.FilePostResponse>(requestInfo, global::AEL.Core.Docling.Gamma.V1.ConvertNamespace.FileNamespace.FileRequestBuilder.FilePostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Process File
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "multipart/form-data", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.V1.ConvertNamespace.FileNamespace.FileRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::AEL.Core.Docling.Gamma.V1.ConvertNamespace.FileNamespace.FileRequestBuilder WithUrl(string rawUrl)
        {
            return new global::AEL.Core.Docling.Gamma.V1.ConvertNamespace.FileNamespace.FileRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentResponse"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.PresignedUrlConvertDocumentResponse"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FilePostResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentResponse? ConvertDocumentResponse { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentResponse ConvertDocumentResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.PresignedUrlConvertDocumentResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.PresignedUrlConvertDocumentResponse? PresignedUrlConvertDocumentResponse { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.PresignedUrlConvertDocumentResponse PresignedUrlConvertDocumentResponse { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.V1.ConvertNamespace.FileNamespace.FileRequestBuilder.FilePostResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::AEL.Core.Docling.Gamma.V1.ConvertNamespace.FileNamespace.FileRequestBuilder.FilePostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::AEL.Core.Docling.Gamma.V1.ConvertNamespace.FileNamespace.FileRequestBuilder.FilePostResponse();
                result.ConvertDocumentResponse = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentResponse();
                result.PresignedUrlConvertDocumentResponse = new global::AEL.Core.Docling.Gamma.Models.PresignedUrlConvertDocumentResponse();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ConvertDocumentResponse != null || PresignedUrlConvertDocumentResponse != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ConvertDocumentResponse, PresignedUrlConvertDocumentResponse);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentResponse>(null, ConvertDocumentResponse, PresignedUrlConvertDocumentResponse);
            }
        }
    }
}
#pragma warning restore CS0618
