// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AEL.Core.Docling.Gamma.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConvertDocumentsRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The options property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions? Options { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions Options { get; set; }
#endif
        /// <summary>The sources property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest.ConvertDocumentsRequest_sources>? Sources { get; set; }
#nullable restore
#else
        public List<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest.ConvertDocumentsRequest_sources> Sources { get; set; }
#endif
        /// <summary>The target property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest.ConvertDocumentsRequest_target? Target { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest.ConvertDocumentsRequest_target Target { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "options", n => { Options = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions>(global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.CreateFromDiscriminatorValue); } },
                { "sources", n => { Sources = n.GetCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest.ConvertDocumentsRequest_sources>(global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest.ConvertDocumentsRequest_sources.CreateFromDiscriminatorValue)?.AsList(); } },
                { "target", n => { Target = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest.ConvertDocumentsRequest_target>(global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest.ConvertDocumentsRequest_target.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions>("options", Options);
            writer.WriteCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest.ConvertDocumentsRequest_sources>("sources", Sources);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest.ConvertDocumentsRequest_target>("target", Target);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::AEL.Core.Docling.Gamma.Models.FileSourceRequest"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.HttpSourceRequest"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.S3SourceRequest"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ConvertDocumentsRequest_sources : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.FileSourceRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.FileSourceRequest? FileSourceRequest { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.FileSourceRequest FileSourceRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.HttpSourceRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.HttpSourceRequest? HttpSourceRequest { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.HttpSourceRequest HttpSourceRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.S3SourceRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.S3SourceRequest? S3SourceRequest { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.S3SourceRequest S3SourceRequest { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest.ConvertDocumentsRequest_sources"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest.ConvertDocumentsRequest_sources CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("kind")?.GetStringValue();
                var result = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest.ConvertDocumentsRequest_sources();
                if("file".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.FileSourceRequest = new global::AEL.Core.Docling.Gamma.Models.FileSourceRequest();
                }
                else if("http".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.HttpSourceRequest = new global::AEL.Core.Docling.Gamma.Models.HttpSourceRequest();
                }
                else if("s3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.S3SourceRequest = new global::AEL.Core.Docling.Gamma.Models.S3SourceRequest();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(FileSourceRequest != null)
                {
                    return FileSourceRequest.GetFieldDeserializers();
                }
                else if(HttpSourceRequest != null)
                {
                    return HttpSourceRequest.GetFieldDeserializers();
                }
                else if(S3SourceRequest != null)
                {
                    return S3SourceRequest.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(FileSourceRequest != null)
                {
                    writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.FileSourceRequest>(null, FileSourceRequest);
                }
                else if(HttpSourceRequest != null)
                {
                    writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.HttpSourceRequest>(null, HttpSourceRequest);
                }
                else if(S3SourceRequest != null)
                {
                    writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.S3SourceRequest>(null, S3SourceRequest);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::AEL.Core.Docling.Gamma.Models.InBodyTarget"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.PutTarget"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.S3Target"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.ZipTarget"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ConvertDocumentsRequest_target : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.InBodyTarget"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.InBodyTarget? InBodyTarget { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.InBodyTarget InBodyTarget { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.PutTarget"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.PutTarget? PutTarget { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.PutTarget PutTarget { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.S3Target"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.S3Target? S3Target { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.S3Target S3Target { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.ZipTarget"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.ZipTarget? ZipTarget { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.ZipTarget ZipTarget { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest.ConvertDocumentsRequest_target"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest.ConvertDocumentsRequest_target CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("kind")?.GetStringValue();
                var result = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequest.ConvertDocumentsRequest_target();
                if("inbody".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InBodyTarget = new global::AEL.Core.Docling.Gamma.Models.InBodyTarget();
                }
                else if("put".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PutTarget = new global::AEL.Core.Docling.Gamma.Models.PutTarget();
                }
                else if("s3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.S3Target = new global::AEL.Core.Docling.Gamma.Models.S3Target();
                }
                else if("zip".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ZipTarget = new global::AEL.Core.Docling.Gamma.Models.ZipTarget();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(InBodyTarget != null)
                {
                    return InBodyTarget.GetFieldDeserializers();
                }
                else if(PutTarget != null)
                {
                    return PutTarget.GetFieldDeserializers();
                }
                else if(S3Target != null)
                {
                    return S3Target.GetFieldDeserializers();
                }
                else if(ZipTarget != null)
                {
                    return ZipTarget.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(InBodyTarget != null)
                {
                    writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.InBodyTarget>(null, InBodyTarget);
                }
                else if(PutTarget != null)
                {
                    writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.PutTarget>(null, PutTarget);
                }
                else if(S3Target != null)
                {
                    writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.S3Target>(null, S3Target);
                }
                else if(ZipTarget != null)
                {
                    writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ZipTarget>(null, ZipTarget);
                }
            }
        }
    }
}
#pragma warning restore CS0618
