// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AEL.Core.Docling.Gamma.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConvertDocumentResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The document property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.ExportDocumentResponse? Document { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.ExportDocumentResponse Document { get; set; }
#endif
        /// <summary>The errors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AEL.Core.Docling.Gamma.Models.ErrorItem>? Errors { get; set; }
#nullable restore
#else
        public List<global::AEL.Core.Docling.Gamma.Models.ErrorItem> Errors { get; set; }
#endif
        /// <summary>The processing_time property</summary>
        public double? ProcessingTime { get; set; }
        /// <summary>The status property</summary>
        public global::AEL.Core.Docling.Gamma.Models.ConversionStatus? Status { get; set; }
        /// <summary>The timings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentResponse_timings? Timings { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentResponse_timings Timings { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AEL.Core.Docling.Gamma.Models.ConvertDocumentResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "document", n => { Document = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.ExportDocumentResponse>(global::AEL.Core.Docling.Gamma.Models.ExportDocumentResponse.CreateFromDiscriminatorValue); } },
                { "errors", n => { Errors = n.GetCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.ErrorItem>(global::AEL.Core.Docling.Gamma.Models.ErrorItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "processing_time", n => { ProcessingTime = n.GetDoubleValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::AEL.Core.Docling.Gamma.Models.ConversionStatus>(); } },
                { "timings", n => { Timings = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentResponse_timings>(global::AEL.Core.Docling.Gamma.Models.ConvertDocumentResponse_timings.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ExportDocumentResponse>("document", Document);
            writer.WriteCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.ErrorItem>("errors", Errors);
            writer.WriteDoubleValue("processing_time", ProcessingTime);
            writer.WriteEnumValue<global::AEL.Core.Docling.Gamma.Models.ConversionStatus>("status", Status);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentResponse_timings>("timings", Timings);
        }
    }
}
#pragma warning restore CS0618
