// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AEL.Core.Docling.Gamma.Models
{
    /// <summary>
    /// Conversion options.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConvertDocumentsRequestOptions : IParsable
    {
        /// <summary>Abort on error if enabled. Boolean. Optional, defaults to false.</summary>
        public bool? AbortOnError { get; set; }
        /// <summary>Custom code/formula extraction configuration including model spec and engine options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_code_formula_custom_config? CodeFormulaCustomConfig { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_code_formula_custom_config CodeFormulaCustomConfig { get; set; }
#endif
        /// <summary>Preset ID for code/formula extraction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_code_formula_preset? CodeFormulaPreset { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_code_formula_preset CodeFormulaPreset { get; set; }
#endif
        /// <summary>If enabled, extract numeric data from charts. Boolean. Optional, defaults to false.</summary>
        public bool? DoChartExtraction { get; set; }
        /// <summary>If enabled, perform OCR code enrichment. Boolean. Optional, defaults to false.</summary>
        public bool? DoCodeEnrichment { get; set; }
        /// <summary>The timeout for processing each document, in seconds.</summary>
        public double? DocumentTimeout { get; set; }
        /// <summary>If enabled, perform formula OCR, return LaTeX code. Boolean. Optional, defaults to false.</summary>
        public bool? DoFormulaEnrichment { get; set; }
        /// <summary>If enabled, the bitmap content will be processed using OCR. Boolean. Optional, defaults to true</summary>
        public bool? DoOcr { get; set; }
        /// <summary>If enabled, classify pictures in documents. Boolean. Optional, defaults to false.</summary>
        public bool? DoPictureClassification { get; set; }
        /// <summary>If enabled, describe pictures in documents. Boolean. Optional, defaults to false.</summary>
        public bool? DoPictureDescription { get; set; }
        /// <summary>If enabled, the table structure will be extracted. Boolean. Optional, defaults to true.</summary>
        public bool? DoTableStructure { get; set; }
        /// <summary>If enabled, replace existing text with OCR-generated text over content. Boolean. Optional, defaults to false.</summary>
        public bool? ForceOcr { get; set; }
        /// <summary>Input format(s) to convert from. String or list of strings. Allowed values: docx, pptx, html, image, pdf, asciidoc, md, csv, xlsx, xml_uspto, xml_jats, mets_gbs, json_docling, audio, vtt, latex. Optional, defaults to all formats.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AEL.Core.Docling.Gamma.Models.InputFormat?>? FromFormats { get; set; }
#nullable restore
#else
        public List<global::AEL.Core.Docling.Gamma.Models.InputFormat?> FromFormats { get; set; }
#endif
        /// <summary>Image export mode for the document (in case of JSON, Markdown or HTML). Allowed values: placeholder, embedded, referenced. Optional, defaults to Embedded.</summary>
        public global::AEL.Core.Docling.Gamma.Models.ImageRefMode? ImageExportMode { get; set; }
        /// <summary>Scale factor for images. Float. Optional, defaults to 2.0.</summary>
        public double? ImagesScale { get; set; }
        /// <summary>If enabled, images will be extracted from the document. Boolean. Optional, defaults to true.</summary>
        public bool? IncludeImages { get; set; }
        /// <summary>Custom configuration for layout model. Use this to specify a non-default kind with its options. The &apos;kind&apos; field in the config dict determines which layout implementation to use. If not specified, uses the default kind with preset configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? LayoutCustomConfig { get; set; }
#nullable restore
#else
        public UntypedNode LayoutCustomConfig { get; set; }
#endif
        /// <summary>Add this placeholder between pages in the markdown output.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MdPageBreakPlaceholder { get; set; }
#nullable restore
#else
        public string MdPageBreakPlaceholder { get; set; }
#endif
        /// <summary>The OCR engine to use. String. Allowed values: auto, easyocr, ocrmac, rapidocr, tesserocr, tesseract. Optional, defaults to easyocr.</summary>
        public global::AEL.Core.Docling.Gamma.Models.Ocr_engines_enum? OcrEngine { get; set; }
        /// <summary>List of languages used by the OCR engine. Note that each OCR engine has different values for the language names. String or list of strings. Optional, defaults to empty.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_ocr_lang? OcrLang { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_ocr_lang OcrLang { get; set; }
#endif
        /// <summary>Only convert a range of pages. The page number starts at 1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? PageRange { get; set; }
#nullable restore
#else
        public UntypedNode PageRange { get; set; }
#endif
        /// <summary>The PDF backend to use. String. Allowed values: pypdfium2, docling_parse, dlparse_v1, dlparse_v2, dlparse_v4. Optional, defaults to docling_parse.</summary>
        public global::AEL.Core.Docling.Gamma.Models.PdfBackend? PdfBackend { get; set; }
        /// <summary>DEPRECATED: API details for using a vision-language model in the picture description. This parameter is mutually exclusive with picture_description_local. Please migrate to picture_description_preset or picture_description_custom_config.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.PictureDescriptionApi? PictureDescriptionApi { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.PictureDescriptionApi PictureDescriptionApi { get; set; }
#endif
        /// <summary>Minimum percentage of the area for a picture to be processed with the models.</summary>
        public double? PictureDescriptionAreaThreshold { get; set; }
        /// <summary>Custom picture description configuration including model spec and engine options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_picture_description_custom_config? PictureDescriptionCustomConfig { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_picture_description_custom_config PictureDescriptionCustomConfig { get; set; }
#endif
        /// <summary>DEPRECATED: Options for running a local vision-language model in the picture description. The parameters refer to a model hosted on Hugging Face. This parameter is mutually exclusive with picture_description_api. Please migrate to picture_description_preset or picture_description_custom_config.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.PictureDescriptionLocal? PictureDescriptionLocal { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.PictureDescriptionLocal PictureDescriptionLocal { get; set; }
#endif
        /// <summary>Preset ID for picture description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_picture_description_preset? PictureDescriptionPreset { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_picture_description_preset PictureDescriptionPreset { get; set; }
#endif
        /// <summary>Choose the pipeline to process PDF or image files.</summary>
        public global::AEL.Core.Docling.Gamma.Models.ProcessingPipeline? Pipeline { get; set; }
        /// <summary>If true, matches table cells predictions back to PDF cells. Can break table output if PDF cells are merged across table columns. If false, let table structure model define the text cells, ignore PDF cells.</summary>
        public bool? TableCellMatching { get; set; }
        /// <summary>Mode to use for table structure, String. Allowed values: fast, accurate. Optional, defaults to accurate.</summary>
        public global::AEL.Core.Docling.Gamma.Models.TableFormerMode? TableMode { get; set; }
        /// <summary>Custom configuration for table structure model. Use this to specify a non-default kind with its options. The &apos;kind&apos; field in the config dict determines which table structure implementation to use. If not specified, uses the default kind with preset configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? TableStructureCustomConfig { get; set; }
#nullable restore
#else
        public UntypedNode TableStructureCustomConfig { get; set; }
#endif
        /// <summary>Output format(s) to convert to. String or list of strings. Allowed values: md, json, yaml, html, html_split_page, text, doctags. Optional, defaults to Markdown.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AEL.Core.Docling.Gamma.Models.OutputFormat?>? ToFormats { get; set; }
#nullable restore
#else
        public List<global::AEL.Core.Docling.Gamma.Models.OutputFormat?> ToFormats { get; set; }
#endif
        /// <summary>Custom VLM configuration including model spec and engine options. Only available if admin allows it. Must include &apos;model_spec&apos; and &apos;engine_options&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_vlm_pipeline_custom_config? VlmPipelineCustomConfig { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_vlm_pipeline_custom_config VlmPipelineCustomConfig { get; set; }
#endif
        /// <summary>DEPRECATED: Preset of local and API models for the vlm pipeline. This parameter is mutually exclusive with vlm_pipeline_model_local and vlm_pipeline_model_api. Use the other options for more parameters. Please migrate to vlm_pipeline_preset or vlm_pipeline_custom_config.</summary>
        [Obsolete("")]
        public global::AEL.Core.Docling.Gamma.Models.VlmModelType? VlmPipelineModel { get; set; }
        /// <summary>DEPRECATED: API details for using a vision-language model for the vlm pipeline. This parameter is mutually exclusive with vlm_pipeline_model_local and vlm_pipeline_model. Please migrate to vlm_pipeline_preset or vlm_pipeline_custom_config.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.VlmModelApi? VlmPipelineModelApi { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.VlmModelApi VlmPipelineModelApi { get; set; }
#endif
        /// <summary>DEPRECATED: Options for running a local vision-language model for the vlm pipeline. The parameters refer to a model hosted on Hugging Face. This parameter is mutually exclusive with vlm_pipeline_model_api and vlm_pipeline_model. Please migrate to vlm_pipeline_preset or vlm_pipeline_custom_config.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.VlmModelLocal? VlmPipelineModelLocal { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.VlmModelLocal VlmPipelineModelLocal { get; set; }
#endif
        /// <summary>Preset ID to use (e.g., &quot;default&quot;, &quot;granite_docling&quot;). Use &quot;default&quot; for stable, admin-controlled configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_vlm_pipeline_preset? VlmPipelinePreset { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_vlm_pipeline_preset VlmPipelinePreset { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions"/> and sets the default values.
        /// </summary>
        public ConvertDocumentsRequestOptions()
        {
            ImageExportMode = global::AEL.Core.Docling.Gamma.Models.ImageRefMode.Embedded;
            OcrEngine = global::AEL.Core.Docling.Gamma.Models.Ocr_engines_enum.Easyocr;
            PdfBackend = global::AEL.Core.Docling.Gamma.Models.PdfBackend.Docling_parse;
            Pipeline = global::AEL.Core.Docling.Gamma.Models.ProcessingPipeline.Standard;
            TableMode = global::AEL.Core.Docling.Gamma.Models.TableFormerMode.Accurate;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "abort_on_error", n => { AbortOnError = n.GetBoolValue(); } },
                { "code_formula_custom_config", n => { CodeFormulaCustomConfig = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_code_formula_custom_config>(global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_code_formula_custom_config.CreateFromDiscriminatorValue); } },
                { "code_formula_preset", n => { CodeFormulaPreset = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_code_formula_preset>(global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_code_formula_preset.CreateFromDiscriminatorValue); } },
                { "do_chart_extraction", n => { DoChartExtraction = n.GetBoolValue(); } },
                { "do_code_enrichment", n => { DoCodeEnrichment = n.GetBoolValue(); } },
                { "do_formula_enrichment", n => { DoFormulaEnrichment = n.GetBoolValue(); } },
                { "do_ocr", n => { DoOcr = n.GetBoolValue(); } },
                { "do_picture_classification", n => { DoPictureClassification = n.GetBoolValue(); } },
                { "do_picture_description", n => { DoPictureDescription = n.GetBoolValue(); } },
                { "do_table_structure", n => { DoTableStructure = n.GetBoolValue(); } },
                { "document_timeout", n => { DocumentTimeout = n.GetDoubleValue(); } },
                { "force_ocr", n => { ForceOcr = n.GetBoolValue(); } },
                { "from_formats", n => { FromFormats = n.GetCollectionOfEnumValues<global::AEL.Core.Docling.Gamma.Models.InputFormat>()?.AsList(); } },
                { "image_export_mode", n => { ImageExportMode = n.GetEnumValue<global::AEL.Core.Docling.Gamma.Models.ImageRefMode>(); } },
                { "images_scale", n => { ImagesScale = n.GetDoubleValue(); } },
                { "include_images", n => { IncludeImages = n.GetBoolValue(); } },
                { "layout_custom_config", n => { LayoutCustomConfig = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "md_page_break_placeholder", n => { MdPageBreakPlaceholder = n.GetStringValue(); } },
                { "ocr_engine", n => { OcrEngine = n.GetEnumValue<global::AEL.Core.Docling.Gamma.Models.Ocr_engines_enum>(); } },
                { "ocr_lang", n => { OcrLang = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_ocr_lang>(global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_ocr_lang.CreateFromDiscriminatorValue); } },
                { "page_range", n => { PageRange = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "pdf_backend", n => { PdfBackend = n.GetEnumValue<global::AEL.Core.Docling.Gamma.Models.PdfBackend>(); } },
                { "picture_description_api", n => { PictureDescriptionApi = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.PictureDescriptionApi>(global::AEL.Core.Docling.Gamma.Models.PictureDescriptionApi.CreateFromDiscriminatorValue); } },
                { "picture_description_area_threshold", n => { PictureDescriptionAreaThreshold = n.GetDoubleValue(); } },
                { "picture_description_custom_config", n => { PictureDescriptionCustomConfig = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_picture_description_custom_config>(global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_picture_description_custom_config.CreateFromDiscriminatorValue); } },
                { "picture_description_local", n => { PictureDescriptionLocal = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.PictureDescriptionLocal>(global::AEL.Core.Docling.Gamma.Models.PictureDescriptionLocal.CreateFromDiscriminatorValue); } },
                { "picture_description_preset", n => { PictureDescriptionPreset = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_picture_description_preset>(global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_picture_description_preset.CreateFromDiscriminatorValue); } },
                { "pipeline", n => { Pipeline = n.GetEnumValue<global::AEL.Core.Docling.Gamma.Models.ProcessingPipeline>(); } },
                { "table_cell_matching", n => { TableCellMatching = n.GetBoolValue(); } },
                { "table_mode", n => { TableMode = n.GetEnumValue<global::AEL.Core.Docling.Gamma.Models.TableFormerMode>(); } },
                { "table_structure_custom_config", n => { TableStructureCustomConfig = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "to_formats", n => { ToFormats = n.GetCollectionOfEnumValues<global::AEL.Core.Docling.Gamma.Models.OutputFormat>()?.AsList(); } },
                { "vlm_pipeline_custom_config", n => { VlmPipelineCustomConfig = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_vlm_pipeline_custom_config>(global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_vlm_pipeline_custom_config.CreateFromDiscriminatorValue); } },
                { "vlm_pipeline_model", n => { VlmPipelineModel = n.GetEnumValue<global::AEL.Core.Docling.Gamma.Models.VlmModelType>(); } },
                { "vlm_pipeline_model_api", n => { VlmPipelineModelApi = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.VlmModelApi>(global::AEL.Core.Docling.Gamma.Models.VlmModelApi.CreateFromDiscriminatorValue); } },
                { "vlm_pipeline_model_local", n => { VlmPipelineModelLocal = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.VlmModelLocal>(global::AEL.Core.Docling.Gamma.Models.VlmModelLocal.CreateFromDiscriminatorValue); } },
                { "vlm_pipeline_preset", n => { VlmPipelinePreset = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_vlm_pipeline_preset>(global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_vlm_pipeline_preset.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("abort_on_error", AbortOnError);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_code_formula_custom_config>("code_formula_custom_config", CodeFormulaCustomConfig);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_code_formula_preset>("code_formula_preset", CodeFormulaPreset);
            writer.WriteBoolValue("do_chart_extraction", DoChartExtraction);
            writer.WriteBoolValue("do_code_enrichment", DoCodeEnrichment);
            writer.WriteDoubleValue("document_timeout", DocumentTimeout);
            writer.WriteBoolValue("do_formula_enrichment", DoFormulaEnrichment);
            writer.WriteBoolValue("do_ocr", DoOcr);
            writer.WriteBoolValue("do_picture_classification", DoPictureClassification);
            writer.WriteBoolValue("do_picture_description", DoPictureDescription);
            writer.WriteBoolValue("do_table_structure", DoTableStructure);
            writer.WriteBoolValue("force_ocr", ForceOcr);
            writer.WriteCollectionOfEnumValues<global::AEL.Core.Docling.Gamma.Models.InputFormat>("from_formats", FromFormats);
            writer.WriteEnumValue<global::AEL.Core.Docling.Gamma.Models.ImageRefMode>("image_export_mode", ImageExportMode);
            writer.WriteDoubleValue("images_scale", ImagesScale);
            writer.WriteBoolValue("include_images", IncludeImages);
            writer.WriteObjectValue<UntypedNode>("layout_custom_config", LayoutCustomConfig);
            writer.WriteStringValue("md_page_break_placeholder", MdPageBreakPlaceholder);
            writer.WriteEnumValue<global::AEL.Core.Docling.Gamma.Models.Ocr_engines_enum>("ocr_engine", OcrEngine);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_ocr_lang>("ocr_lang", OcrLang);
            writer.WriteObjectValue<UntypedNode>("page_range", PageRange);
            writer.WriteEnumValue<global::AEL.Core.Docling.Gamma.Models.PdfBackend>("pdf_backend", PdfBackend);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.PictureDescriptionApi>("picture_description_api", PictureDescriptionApi);
            writer.WriteDoubleValue("picture_description_area_threshold", PictureDescriptionAreaThreshold);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_picture_description_custom_config>("picture_description_custom_config", PictureDescriptionCustomConfig);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.PictureDescriptionLocal>("picture_description_local", PictureDescriptionLocal);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_picture_description_preset>("picture_description_preset", PictureDescriptionPreset);
            writer.WriteEnumValue<global::AEL.Core.Docling.Gamma.Models.ProcessingPipeline>("pipeline", Pipeline);
            writer.WriteBoolValue("table_cell_matching", TableCellMatching);
            writer.WriteEnumValue<global::AEL.Core.Docling.Gamma.Models.TableFormerMode>("table_mode", TableMode);
            writer.WriteObjectValue<UntypedNode>("table_structure_custom_config", TableStructureCustomConfig);
            writer.WriteCollectionOfEnumValues<global::AEL.Core.Docling.Gamma.Models.OutputFormat>("to_formats", ToFormats);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_vlm_pipeline_custom_config>("vlm_pipeline_custom_config", VlmPipelineCustomConfig);
            writer.WriteEnumValue<global::AEL.Core.Docling.Gamma.Models.VlmModelType>("vlm_pipeline_model", VlmPipelineModel);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.VlmModelApi>("vlm_pipeline_model_api", VlmPipelineModelApi);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.VlmModelLocal>("vlm_pipeline_model_local", VlmPipelineModelLocal);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_vlm_pipeline_preset>("vlm_pipeline_preset", VlmPipelinePreset);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::AEL.Core.Docling.Gamma.Models.CodeFormulaVlmOptions"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_code_formula_custom_configMember1"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_code_formula_custom_configMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ConvertDocumentsRequestOptions_code_formula_custom_config : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.CodeFormulaVlmOptions"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.CodeFormulaVlmOptions? CodeFormulaVlmOptions { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.CodeFormulaVlmOptions CodeFormulaVlmOptions { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_code_formula_custom_configMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_code_formula_custom_configMember1? ConvertDocumentsRequestOptionsCodeFormulaCustomConfigMember1 { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_code_formula_custom_configMember1 ConvertDocumentsRequestOptionsCodeFormulaCustomConfigMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_code_formula_custom_configMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_code_formula_custom_configMember2? ConvertDocumentsRequestOptionsCodeFormulaCustomConfigMember2 { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_code_formula_custom_configMember2 ConvertDocumentsRequestOptionsCodeFormulaCustomConfigMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_code_formula_custom_config"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_code_formula_custom_config CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_code_formula_custom_config();
                result.CodeFormulaVlmOptions = new global::AEL.Core.Docling.Gamma.Models.CodeFormulaVlmOptions();
                result.ConvertDocumentsRequestOptionsCodeFormulaCustomConfigMember1 = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_code_formula_custom_configMember1();
                result.ConvertDocumentsRequestOptionsCodeFormulaCustomConfigMember2 = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_code_formula_custom_configMember2();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CodeFormulaVlmOptions != null || ConvertDocumentsRequestOptionsCodeFormulaCustomConfigMember1 != null || ConvertDocumentsRequestOptionsCodeFormulaCustomConfigMember2 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CodeFormulaVlmOptions, ConvertDocumentsRequestOptionsCodeFormulaCustomConfigMember1, ConvertDocumentsRequestOptionsCodeFormulaCustomConfigMember2);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.CodeFormulaVlmOptions>(null, CodeFormulaVlmOptions, ConvertDocumentsRequestOptionsCodeFormulaCustomConfigMember1, ConvertDocumentsRequestOptionsCodeFormulaCustomConfigMember2);
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_code_formula_presetMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ConvertDocumentsRequestOptions_code_formula_preset : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_code_formula_presetMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_code_formula_presetMember1? ConvertDocumentsRequestOptionsCodeFormulaPresetMember1 { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_code_formula_presetMember1 ConvertDocumentsRequestOptionsCodeFormulaPresetMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_code_formula_preset"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_code_formula_preset CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_code_formula_preset();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ConvertDocumentsRequestOptionsCodeFormulaPresetMember1 = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_code_formula_presetMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ConvertDocumentsRequestOptionsCodeFormulaPresetMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ConvertDocumentsRequestOptionsCodeFormulaPresetMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_code_formula_presetMember1>(null, ConvertDocumentsRequestOptionsCodeFormulaPresetMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_ocr_langMember1"/>, List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ConvertDocumentsRequestOptions_ocr_lang : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_ocr_langMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_ocr_langMember1? ConvertDocumentsRequestOptionsOcrLangMember1 { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_ocr_langMember1 ConvertDocumentsRequestOptionsOcrLangMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_ocr_lang"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_ocr_lang CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_ocr_lang();
                if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ConvertDocumentsRequestOptionsOcrLangMember1 = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_ocr_langMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ConvertDocumentsRequestOptionsOcrLangMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ConvertDocumentsRequestOptionsOcrLangMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
                else {
                    writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_ocr_langMember1>(null, ConvertDocumentsRequestOptionsOcrLangMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_picture_description_custom_configMember1"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_picture_description_custom_configMember2"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.PictureDescriptionVlmEngineOptions"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ConvertDocumentsRequestOptions_picture_description_custom_config : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_picture_description_custom_configMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_picture_description_custom_configMember1? ConvertDocumentsRequestOptionsPictureDescriptionCustomConfigMember1 { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_picture_description_custom_configMember1 ConvertDocumentsRequestOptionsPictureDescriptionCustomConfigMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_picture_description_custom_configMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_picture_description_custom_configMember2? ConvertDocumentsRequestOptionsPictureDescriptionCustomConfigMember2 { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_picture_description_custom_configMember2 ConvertDocumentsRequestOptionsPictureDescriptionCustomConfigMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.PictureDescriptionVlmEngineOptions"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.PictureDescriptionVlmEngineOptions? PictureDescriptionVlmEngineOptions { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.PictureDescriptionVlmEngineOptions PictureDescriptionVlmEngineOptions { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_picture_description_custom_config"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_picture_description_custom_config CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_picture_description_custom_config();
                result.ConvertDocumentsRequestOptionsPictureDescriptionCustomConfigMember1 = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_picture_description_custom_configMember1();
                result.ConvertDocumentsRequestOptionsPictureDescriptionCustomConfigMember2 = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_picture_description_custom_configMember2();
                result.PictureDescriptionVlmEngineOptions = new global::AEL.Core.Docling.Gamma.Models.PictureDescriptionVlmEngineOptions();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ConvertDocumentsRequestOptionsPictureDescriptionCustomConfigMember1 != null || ConvertDocumentsRequestOptionsPictureDescriptionCustomConfigMember2 != null || PictureDescriptionVlmEngineOptions != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ConvertDocumentsRequestOptionsPictureDescriptionCustomConfigMember1, ConvertDocumentsRequestOptionsPictureDescriptionCustomConfigMember2, PictureDescriptionVlmEngineOptions);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_picture_description_custom_configMember1>(null, ConvertDocumentsRequestOptionsPictureDescriptionCustomConfigMember1, ConvertDocumentsRequestOptionsPictureDescriptionCustomConfigMember2, PictureDescriptionVlmEngineOptions);
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_picture_description_presetMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ConvertDocumentsRequestOptions_picture_description_preset : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_picture_description_presetMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_picture_description_presetMember1? ConvertDocumentsRequestOptionsPictureDescriptionPresetMember1 { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_picture_description_presetMember1 ConvertDocumentsRequestOptionsPictureDescriptionPresetMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_picture_description_preset"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_picture_description_preset CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_picture_description_preset();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ConvertDocumentsRequestOptionsPictureDescriptionPresetMember1 = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_picture_description_presetMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ConvertDocumentsRequestOptionsPictureDescriptionPresetMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ConvertDocumentsRequestOptionsPictureDescriptionPresetMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_picture_description_presetMember1>(null, ConvertDocumentsRequestOptionsPictureDescriptionPresetMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_vlm_pipeline_custom_configMember1"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_vlm_pipeline_custom_configMember2"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ConvertDocumentsRequestOptions_vlm_pipeline_custom_config : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_vlm_pipeline_custom_configMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_vlm_pipeline_custom_configMember1? ConvertDocumentsRequestOptionsVlmPipelineCustomConfigMember1 { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_vlm_pipeline_custom_configMember1 ConvertDocumentsRequestOptionsVlmPipelineCustomConfigMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_vlm_pipeline_custom_configMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_vlm_pipeline_custom_configMember2? ConvertDocumentsRequestOptionsVlmPipelineCustomConfigMember2 { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_vlm_pipeline_custom_configMember2 ConvertDocumentsRequestOptionsVlmPipelineCustomConfigMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions? VlmConvertOptions { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions VlmConvertOptions { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_vlm_pipeline_custom_config"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_vlm_pipeline_custom_config CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_vlm_pipeline_custom_config();
                result.ConvertDocumentsRequestOptionsVlmPipelineCustomConfigMember1 = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_vlm_pipeline_custom_configMember1();
                result.ConvertDocumentsRequestOptionsVlmPipelineCustomConfigMember2 = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_vlm_pipeline_custom_configMember2();
                result.VlmConvertOptions = new global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ConvertDocumentsRequestOptionsVlmPipelineCustomConfigMember1 != null || ConvertDocumentsRequestOptionsVlmPipelineCustomConfigMember2 != null || VlmConvertOptions != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ConvertDocumentsRequestOptionsVlmPipelineCustomConfigMember1, ConvertDocumentsRequestOptionsVlmPipelineCustomConfigMember2, VlmConvertOptions);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_vlm_pipeline_custom_configMember1>(null, ConvertDocumentsRequestOptionsVlmPipelineCustomConfigMember1, ConvertDocumentsRequestOptionsVlmPipelineCustomConfigMember2, VlmConvertOptions);
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_vlm_pipeline_presetMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ConvertDocumentsRequestOptions_vlm_pipeline_preset : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_vlm_pipeline_presetMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_vlm_pipeline_presetMember1? ConvertDocumentsRequestOptionsVlmPipelinePresetMember1 { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_vlm_pipeline_presetMember1 ConvertDocumentsRequestOptionsVlmPipelinePresetMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_vlm_pipeline_preset"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_vlm_pipeline_preset CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions.ConvertDocumentsRequestOptions_vlm_pipeline_preset();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ConvertDocumentsRequestOptionsVlmPipelinePresetMember1 = new global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_vlm_pipeline_presetMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ConvertDocumentsRequestOptionsVlmPipelinePresetMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ConvertDocumentsRequestOptionsVlmPipelinePresetMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.ConvertDocumentsRequestOptions_vlm_pipeline_presetMember1>(null, ConvertDocumentsRequestOptionsVlmPipelinePresetMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
