// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AEL.Core.Docling.Gamma.Models
{
    /// <summary>
    /// DoclingDocument.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DoclingDocument : IParsable
    {
        /// <summary>GroupItem.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.GroupItem? Body { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.GroupItem Body { get; set; }
#endif
        /// <summary>The form_items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AEL.Core.Docling.Gamma.Models.FormItem>? FormItems { get; set; }
#nullable restore
#else
        public List<global::AEL.Core.Docling.Gamma.Models.FormItem> FormItems { get; set; }
#endif
        /// <summary>GroupItem.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.GroupItem? Furniture { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.GroupItem Furniture { get; set; }
#endif
        /// <summary>The groups property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AEL.Core.Docling.Gamma.Models.DoclingDocument.DoclingDocument_groups>? Groups { get; set; }
#nullable restore
#else
        public List<global::AEL.Core.Docling.Gamma.Models.DoclingDocument.DoclingDocument_groups> Groups { get; set; }
#endif
        /// <summary>The key_value_items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AEL.Core.Docling.Gamma.Models.KeyValueItem>? KeyValueItems { get; set; }
#nullable restore
#else
        public List<global::AEL.Core.Docling.Gamma.Models.KeyValueItem> KeyValueItems { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The origin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.DocumentOrigin? Origin { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.DocumentOrigin Origin { get; set; }
#endif
        /// <summary>The pages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.DoclingDocument_pages? Pages { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.DoclingDocument_pages Pages { get; set; }
#endif
        /// <summary>The pictures property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AEL.Core.Docling.Gamma.Models.PictureItem>? Pictures { get; set; }
#nullable restore
#else
        public List<global::AEL.Core.Docling.Gamma.Models.PictureItem> Pictures { get; set; }
#endif
        /// <summary>The schema_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SchemaName { get; set; }
#nullable restore
#else
        public string SchemaName { get; set; }
#endif
        /// <summary>The tables property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AEL.Core.Docling.Gamma.Models.TableItem>? Tables { get; set; }
#nullable restore
#else
        public List<global::AEL.Core.Docling.Gamma.Models.TableItem> Tables { get; set; }
#endif
        /// <summary>The texts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AEL.Core.Docling.Gamma.Models.DoclingDocument.DoclingDocument_texts>? Texts { get; set; }
#nullable restore
#else
        public List<global::AEL.Core.Docling.Gamma.Models.DoclingDocument.DoclingDocument_texts> Texts { get; set; }
#endif
        /// <summary>The version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::AEL.Core.Docling.Gamma.Models.DoclingDocument"/> and sets the default values.
        /// </summary>
        public DoclingDocument()
        {
            SchemaName = "DoclingDocument";
            Version = "1.9.0";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.DoclingDocument"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AEL.Core.Docling.Gamma.Models.DoclingDocument CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AEL.Core.Docling.Gamma.Models.DoclingDocument();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "body", n => { Body = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.GroupItem>(global::AEL.Core.Docling.Gamma.Models.GroupItem.CreateFromDiscriminatorValue); } },
                { "form_items", n => { FormItems = n.GetCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.FormItem>(global::AEL.Core.Docling.Gamma.Models.FormItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "furniture", n => { Furniture = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.GroupItem>(global::AEL.Core.Docling.Gamma.Models.GroupItem.CreateFromDiscriminatorValue); } },
                { "groups", n => { Groups = n.GetCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.DoclingDocument.DoclingDocument_groups>(global::AEL.Core.Docling.Gamma.Models.DoclingDocument.DoclingDocument_groups.CreateFromDiscriminatorValue)?.AsList(); } },
                { "key_value_items", n => { KeyValueItems = n.GetCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.KeyValueItem>(global::AEL.Core.Docling.Gamma.Models.KeyValueItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "origin", n => { Origin = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.DocumentOrigin>(global::AEL.Core.Docling.Gamma.Models.DocumentOrigin.CreateFromDiscriminatorValue); } },
                { "pages", n => { Pages = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.DoclingDocument_pages>(global::AEL.Core.Docling.Gamma.Models.DoclingDocument_pages.CreateFromDiscriminatorValue); } },
                { "pictures", n => { Pictures = n.GetCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.PictureItem>(global::AEL.Core.Docling.Gamma.Models.PictureItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "schema_name", n => { SchemaName = n.GetStringValue(); } },
                { "tables", n => { Tables = n.GetCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.TableItem>(global::AEL.Core.Docling.Gamma.Models.TableItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "texts", n => { Texts = n.GetCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.DoclingDocument.DoclingDocument_texts>(global::AEL.Core.Docling.Gamma.Models.DoclingDocument.DoclingDocument_texts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "version", n => { Version = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.GroupItem>("body", Body);
            writer.WriteCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.FormItem>("form_items", FormItems);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.GroupItem>("furniture", Furniture);
            writer.WriteCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.DoclingDocument.DoclingDocument_groups>("groups", Groups);
            writer.WriteCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.KeyValueItem>("key_value_items", KeyValueItems);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.DocumentOrigin>("origin", Origin);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.DoclingDocument_pages>("pages", Pages);
            writer.WriteCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.PictureItem>("pictures", Pictures);
            writer.WriteStringValue("schema_name", SchemaName);
            writer.WriteCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.TableItem>("tables", Tables);
            writer.WriteCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.DoclingDocument.DoclingDocument_texts>("texts", Texts);
            writer.WriteStringValue("version", Version);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::AEL.Core.Docling.Gamma.Models.GroupItem"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.InlineGroup"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.ListGroup"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DoclingDocument_groups : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.GroupItem"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.GroupItem? GroupItem { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.GroupItem GroupItem { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.InlineGroup"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.InlineGroup? InlineGroup { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.InlineGroup InlineGroup { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.ListGroup"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.ListGroup? ListGroup { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.ListGroup ListGroup { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.DoclingDocument.DoclingDocument_groups"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::AEL.Core.Docling.Gamma.Models.DoclingDocument.DoclingDocument_groups CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::AEL.Core.Docling.Gamma.Models.DoclingDocument.DoclingDocument_groups();
                result.GroupItem = new global::AEL.Core.Docling.Gamma.Models.GroupItem();
                result.InlineGroup = new global::AEL.Core.Docling.Gamma.Models.InlineGroup();
                result.ListGroup = new global::AEL.Core.Docling.Gamma.Models.ListGroup();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GroupItem != null || InlineGroup != null || ListGroup != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GroupItem, InlineGroup, ListGroup);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.GroupItem>(null, GroupItem, InlineGroup, ListGroup);
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::AEL.Core.Docling.Gamma.Models.CodeItem"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.FormulaItem"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.ListItem"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.SectionHeaderItem"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.TextItem"/>, <see cref="global::AEL.Core.Docling.Gamma.Models.TitleItem"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DoclingDocument_texts : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.CodeItem"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.CodeItem? CodeItem { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.CodeItem CodeItem { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.FormulaItem"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.FormulaItem? FormulaItem { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.FormulaItem FormulaItem { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.ListItem"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.ListItem? ListItem { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.ListItem ListItem { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.SectionHeaderItem"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.SectionHeaderItem? SectionHeaderItem { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.SectionHeaderItem SectionHeaderItem { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.TextItem"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.TextItem? TextItem { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.TextItem TextItem { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.TitleItem"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.TitleItem? TitleItem { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.TitleItem TitleItem { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.DoclingDocument.DoclingDocument_texts"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::AEL.Core.Docling.Gamma.Models.DoclingDocument.DoclingDocument_texts CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::AEL.Core.Docling.Gamma.Models.DoclingDocument.DoclingDocument_texts();
                result.CodeItem = new global::AEL.Core.Docling.Gamma.Models.CodeItem();
                result.FormulaItem = new global::AEL.Core.Docling.Gamma.Models.FormulaItem();
                result.ListItem = new global::AEL.Core.Docling.Gamma.Models.ListItem();
                result.SectionHeaderItem = new global::AEL.Core.Docling.Gamma.Models.SectionHeaderItem();
                result.TextItem = new global::AEL.Core.Docling.Gamma.Models.TextItem();
                result.TitleItem = new global::AEL.Core.Docling.Gamma.Models.TitleItem();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CodeItem != null || FormulaItem != null || ListItem != null || SectionHeaderItem != null || TextItem != null || TitleItem != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CodeItem, FormulaItem, ListItem, SectionHeaderItem, TextItem, TitleItem);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.CodeItem>(null, CodeItem, FormulaItem, ListItem, SectionHeaderItem, TextItem, TitleItem);
            }
        }
    }
}
#pragma warning restore CS0618
