// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AEL.Core.Docling.Gamma.Models
{
    /// <summary>
    /// InlineGroup.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InlineGroup : IParsable
    {
        /// <summary>The children property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AEL.Core.Docling.Gamma.Models.RefItem>? Children { get; set; }
#nullable restore
#else
        public List<global::AEL.Core.Docling.Gamma.Models.RefItem> Children { get; set; }
#endif
        /// <summary>ContentLayer.</summary>
        public global::AEL.Core.Docling.Gamma.Models.ContentLayer? ContentLayer { get; set; }
        /// <summary>The label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>The meta property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.BaseMeta? Meta { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.BaseMeta Meta { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The parent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.RefItem? Parent { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.RefItem Parent { get; set; }
#endif
        /// <summary>The self_ref property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SelfRef { get; set; }
#nullable restore
#else
        public string SelfRef { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::AEL.Core.Docling.Gamma.Models.InlineGroup"/> and sets the default values.
        /// </summary>
        public InlineGroup()
        {
            ContentLayer = global::AEL.Core.Docling.Gamma.Models.ContentLayer.Body;
            Label = "inline";
            Name = "group";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.InlineGroup"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AEL.Core.Docling.Gamma.Models.InlineGroup CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AEL.Core.Docling.Gamma.Models.InlineGroup();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "children", n => { Children = n.GetCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.RefItem>(global::AEL.Core.Docling.Gamma.Models.RefItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "content_layer", n => { ContentLayer = n.GetEnumValue<global::AEL.Core.Docling.Gamma.Models.ContentLayer>(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "meta", n => { Meta = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.BaseMeta>(global::AEL.Core.Docling.Gamma.Models.BaseMeta.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parent", n => { Parent = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.RefItem>(global::AEL.Core.Docling.Gamma.Models.RefItem.CreateFromDiscriminatorValue); } },
                { "self_ref", n => { SelfRef = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.RefItem>("children", Children);
            writer.WriteEnumValue<global::AEL.Core.Docling.Gamma.Models.ContentLayer>("content_layer", ContentLayer);
            writer.WriteStringValue("label", Label);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.BaseMeta>("meta", Meta);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.RefItem>("parent", Parent);
            writer.WriteStringValue("self_ref", SelfRef);
        }
    }
}
#pragma warning restore CS0618
