// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AEL.Core.Docling.Gamma.Models
{
    /// <summary>
    /// Configuration for VLM runtime-based picture description.This is the new implementation that uses the pluggable runtime system with preset support.Supports all runtime types (Transformers, MLX, API, etc.) through the unified runtime interface.Use `from_preset()` to create instances from registered presets.Examples:    # Use preset with default runtime    options = PictureDescriptionVlmEngineOptions.from_preset(&quot;smolvlm&quot;)    # Use preset with runtime override    from docling.datamodel.vlm_engine_options import MlxVlmEngineOptions, VlmEngineType    options = PictureDescriptionVlmEngineOptions.from_preset(        &quot;smolvlm&quot;,        engine_options=MlxVlmEngineOptions(engine_type=VlmEngineType.MLX)    )
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PictureDescriptionVlmEngineOptions : IParsable
    {
        /// <summary>Number of images to process in a single batch during picture description. Higher values improve throughput but increase memory usage. Adjust based on available GPU/CPU memory.</summary>
        public int? BatchSize { get; set; }
        /// <summary>List of picture classification labels to allow for description. Only pictures classified with these labels will be processed. If None, all picture types are allowed unless explicitly denied. Use to focus description on specific image types (e.g., diagrams, charts).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AEL.Core.Docling.Gamma.Models.PictureClassificationLabel>? ClassificationAllow { get; set; }
#nullable restore
#else
        public List<global::AEL.Core.Docling.Gamma.Models.PictureClassificationLabel> ClassificationAllow { get; set; }
#endif
        /// <summary>List of picture classification labels to exclude from description. Pictures classified with these labels will be skipped. If None, no picture types are denied unless not in allow list. Use to exclude unwanted image types (e.g., decorative images, logos).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AEL.Core.Docling.Gamma.Models.PictureClassificationLabel>? ClassificationDeny { get; set; }
#nullable restore
#else
        public List<global::AEL.Core.Docling.Gamma.Models.PictureClassificationLabel> ClassificationDeny { get; set; }
#endif
        /// <summary>Minimum classification confidence score (0.0-1.0) required for a picture to be processed. Pictures with classification confidence below this threshold are skipped. Higher values ensure only confidently classified images are described. Range: 0.0 (no filtering) to 1.0 (maximum confidence).</summary>
        public double? ClassificationMinConfidence { get; set; }
        /// <summary>Runtime configuration (transformers, mlx, api, etc.)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.BaseVlmEngineOptions? EngineOptions { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.BaseVlmEngineOptions EngineOptions { get; set; }
#endif
        /// <summary>Generation configuration for text generation. Controls output length, sampling strategy, temperature, etc.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.PictureDescriptionVlmEngineOptions_generation_config? GenerationConfig { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.PictureDescriptionVlmEngineOptions_generation_config GenerationConfig { get; set; }
#endif
        /// <summary>Model specification with runtime-specific overrides</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.VlmModelSpec? ModelSpec { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.VlmModelSpec ModelSpec { get; set; }
#endif
        /// <summary>Minimum picture area as fraction of page area (0.0-1.0) to trigger description. Pictures smaller than this threshold are skipped. Use lower values (e.g., 0.01) to describe small images.</summary>
        public double? PictureAreaThreshold { get; set; }
        /// <summary>Prompt template for the vision model. Customize to control description style, detail level, or focus.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prompt { get; set; }
#nullable restore
#else
        public string Prompt { get; set; }
#endif
        /// <summary>Scaling factor for image resolution before processing. Higher values (e.g., 2.0) provide more detail for the vision model but increase processing time and memory. Range: 0.5-4.0 typical.</summary>
        public double? Scale { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::AEL.Core.Docling.Gamma.Models.PictureDescriptionVlmEngineOptions"/> and sets the default values.
        /// </summary>
        public PictureDescriptionVlmEngineOptions()
        {
            Prompt = "Describe this image in a few sentences.";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.PictureDescriptionVlmEngineOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AEL.Core.Docling.Gamma.Models.PictureDescriptionVlmEngineOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AEL.Core.Docling.Gamma.Models.PictureDescriptionVlmEngineOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "batch_size", n => { BatchSize = n.GetIntValue(); } },
                { "classification_allow", n => { ClassificationAllow = n.GetCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.PictureClassificationLabel>(global::AEL.Core.Docling.Gamma.Models.PictureClassificationLabel.CreateFromDiscriminatorValue)?.AsList(); } },
                { "classification_deny", n => { ClassificationDeny = n.GetCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.PictureClassificationLabel>(global::AEL.Core.Docling.Gamma.Models.PictureClassificationLabel.CreateFromDiscriminatorValue)?.AsList(); } },
                { "classification_min_confidence", n => { ClassificationMinConfidence = n.GetDoubleValue(); } },
                { "engine_options", n => { EngineOptions = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.BaseVlmEngineOptions>(global::AEL.Core.Docling.Gamma.Models.BaseVlmEngineOptions.CreateFromDiscriminatorValue); } },
                { "generation_config", n => { GenerationConfig = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.PictureDescriptionVlmEngineOptions_generation_config>(global::AEL.Core.Docling.Gamma.Models.PictureDescriptionVlmEngineOptions_generation_config.CreateFromDiscriminatorValue); } },
                { "model_spec", n => { ModelSpec = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.VlmModelSpec>(global::AEL.Core.Docling.Gamma.Models.VlmModelSpec.CreateFromDiscriminatorValue); } },
                { "picture_area_threshold", n => { PictureAreaThreshold = n.GetDoubleValue(); } },
                { "prompt", n => { Prompt = n.GetStringValue(); } },
                { "scale", n => { Scale = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("batch_size", BatchSize);
            writer.WriteCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.PictureClassificationLabel>("classification_allow", ClassificationAllow);
            writer.WriteCollectionOfObjectValues<global::AEL.Core.Docling.Gamma.Models.PictureClassificationLabel>("classification_deny", ClassificationDeny);
            writer.WriteDoubleValue("classification_min_confidence", ClassificationMinConfidence);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.BaseVlmEngineOptions>("engine_options", EngineOptions);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.PictureDescriptionVlmEngineOptions_generation_config>("generation_config", GenerationConfig);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.VlmModelSpec>("model_spec", ModelSpec);
            writer.WriteDoubleValue("picture_area_threshold", PictureAreaThreshold);
            writer.WriteStringValue("prompt", Prompt);
            writer.WriteDoubleValue("scale", Scale);
        }
    }
}
#pragma warning restore CS0618
