// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AEL.Core.Docling.Gamma.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PresignedUrlConvertDocumentResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The num_converted property</summary>
        public int? NumConverted { get; set; }
        /// <summary>The num_failed property</summary>
        public int? NumFailed { get; set; }
        /// <summary>The num_succeeded property</summary>
        public int? NumSucceeded { get; set; }
        /// <summary>The processing_time property</summary>
        public double? ProcessingTime { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.PresignedUrlConvertDocumentResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AEL.Core.Docling.Gamma.Models.PresignedUrlConvertDocumentResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AEL.Core.Docling.Gamma.Models.PresignedUrlConvertDocumentResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "num_converted", n => { NumConverted = n.GetIntValue(); } },
                { "num_failed", n => { NumFailed = n.GetIntValue(); } },
                { "num_succeeded", n => { NumSucceeded = n.GetIntValue(); } },
                { "processing_time", n => { ProcessingTime = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("num_converted", NumConverted);
            writer.WriteIntValue("num_failed", NumFailed);
            writer.WriteIntValue("num_succeeded", NumSucceeded);
            writer.WriteDoubleValue("processing_time", ProcessingTime);
        }
    }
}
#pragma warning restore CS0618
