// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AEL.Core.Docling.Gamma.Models
{
    /// <summary>
    /// Configuration for VLM-based document conversion.This stage uses vision-language models to convert document pages tostructured formats (DocTags, Markdown, etc.). Supports preset-basedconfiguration via StagePresetMixin.Examples:    # Use preset with default runtime    options = VlmConvertOptions.from_preset(&quot;smoldocling&quot;)    # Use preset with runtime override    from docling.datamodel.vlm_engine_options import ApiVlmEngineOptions, VlmEngineType    options = VlmConvertOptions.from_preset(        &quot;smoldocling&quot;,        engine_options=ApiVlmEngineOptions(engine_type=VlmEngineType.API_OLLAMA)    )
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VlmConvertOptions : IParsable
    {
        /// <summary>Batch size for processing multiple pages</summary>
        public int? BatchSize { get; set; }
        /// <summary>Runtime configuration (transformers, mlx, api, etc.)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.BaseVlmEngineOptions? EngineOptions { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.BaseVlmEngineOptions EngineOptions { get; set; }
#endif
        /// <summary>Force use of backend text extraction instead of VLM</summary>
        public bool? ForceBackendText { get; set; }
        /// <summary>Maximum image dimension (width or height)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions.VlmConvertOptions_max_size? MaxSize { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions.VlmConvertOptions_max_size MaxSize { get; set; }
#endif
        /// <summary>Model specification with runtime-specific overrides</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.VlmModelSpec? ModelSpec { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.VlmModelSpec ModelSpec { get; set; }
#endif
        /// <summary>Image scaling factor for preprocessing</summary>
        public double? Scale { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "batch_size", n => { BatchSize = n.GetIntValue(); } },
                { "engine_options", n => { EngineOptions = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.BaseVlmEngineOptions>(global::AEL.Core.Docling.Gamma.Models.BaseVlmEngineOptions.CreateFromDiscriminatorValue); } },
                { "force_backend_text", n => { ForceBackendText = n.GetBoolValue(); } },
                { "max_size", n => { MaxSize = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions.VlmConvertOptions_max_size>(global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions.VlmConvertOptions_max_size.CreateFromDiscriminatorValue); } },
                { "model_spec", n => { ModelSpec = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.VlmModelSpec>(global::AEL.Core.Docling.Gamma.Models.VlmModelSpec.CreateFromDiscriminatorValue); } },
                { "scale", n => { Scale = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("batch_size", BatchSize);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.BaseVlmEngineOptions>("engine_options", EngineOptions);
            writer.WriteBoolValue("force_backend_text", ForceBackendText);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions.VlmConvertOptions_max_size>("max_size", MaxSize);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.VlmModelSpec>("model_spec", ModelSpec);
            writer.WriteDoubleValue("scale", Scale);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions_max_sizeMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class VlmConvertOptions_max_size : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions_max_sizeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions_max_sizeMember1? VlmConvertOptionsMaxSizeMember1 { get; set; }
#nullable restore
#else
            public global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions_max_sizeMember1 VlmConvertOptionsMaxSizeMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions.VlmConvertOptions_max_size"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions.VlmConvertOptions_max_size CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions.VlmConvertOptions_max_size();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.VlmConvertOptionsMaxSizeMember1 = new global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions_max_sizeMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(VlmConvertOptionsMaxSizeMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(VlmConvertOptionsMaxSizeMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.VlmConvertOptions_max_sizeMember1>(null, VlmConvertOptionsMaxSizeMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
