// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AEL.Core.Docling.Gamma.Models
{
    /// <summary>Type of inference engine to use</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VlmEngineType
    {
        [EnumMember(Value = "transformers")]
        #pragma warning disable CS1591
        Transformers,
        #pragma warning restore CS1591
        [EnumMember(Value = "mlx")]
        #pragma warning disable CS1591
        Mlx,
        #pragma warning restore CS1591
        [EnumMember(Value = "vllm")]
        #pragma warning disable CS1591
        Vllm,
        #pragma warning restore CS1591
        [EnumMember(Value = "api")]
        #pragma warning disable CS1591
        Api,
        #pragma warning restore CS1591
        [EnumMember(Value = "api_ollama")]
        #pragma warning disable CS1591
        Api_ollama,
        #pragma warning restore CS1591
        [EnumMember(Value = "api_lmstudio")]
        #pragma warning disable CS1591
        Api_lmstudio,
        #pragma warning restore CS1591
        [EnumMember(Value = "api_openai")]
        #pragma warning disable CS1591
        Api_openai,
        #pragma warning restore CS1591
        [EnumMember(Value = "auto_inline")]
        #pragma warning disable CS1591
        Auto_inline,
        #pragma warning restore CS1591
    }
}
