// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AEL.Core.Docling.Gamma.Models
{
    /// <summary>
    /// Model specification with runtime-specific overrides
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VlmModelSpec : IParsable
    {
        /// <summary>API-specific configuration overrides</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.VlmModelSpec_api_overrides? ApiOverrides { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.VlmModelSpec_api_overrides ApiOverrides { get; set; }
#endif
        /// <summary>Default HuggingFace repository ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultRepoId { get; set; }
#nullable restore
#else
        public string DefaultRepoId { get; set; }
#endif
        /// <summary>Engine-specific configuration overrides</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEL.Core.Docling.Gamma.Models.VlmModelSpec_engine_overrides? EngineOverrides { get; set; }
#nullable restore
#else
        public global::AEL.Core.Docling.Gamma.Models.VlmModelSpec_engine_overrides EngineOverrides { get; set; }
#endif
        /// <summary>Maximum number of new tokens to generate</summary>
        public int? MaxNewTokens { get; set; }
        /// <summary>Human-readable model name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Prompt template for this model</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prompt { get; set; }
#nullable restore
#else
        public string Prompt { get; set; }
#endif
        /// <summary>Expected response format from the model</summary>
        public global::AEL.Core.Docling.Gamma.Models.ResponseFormat? ResponseFormat { get; set; }
        /// <summary>Default model revision</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Revision { get; set; }
#nullable restore
#else
        public string Revision { get; set; }
#endif
        /// <summary>Stop strings for generation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? StopStrings { get; set; }
#nullable restore
#else
        public List<string> StopStrings { get; set; }
#endif
        /// <summary>Set of supported engines (None = all supported)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AEL.Core.Docling.Gamma.Models.VlmEngineType?>? SupportedEngines { get; set; }
#nullable restore
#else
        public List<global::AEL.Core.Docling.Gamma.Models.VlmEngineType?> SupportedEngines { get; set; }
#endif
        /// <summary>Whether to trust remote code for this model</summary>
        public bool? TrustRemoteCode { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::AEL.Core.Docling.Gamma.Models.VlmModelSpec"/> and sets the default values.
        /// </summary>
        public VlmModelSpec()
        {
            Revision = "main";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.VlmModelSpec"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AEL.Core.Docling.Gamma.Models.VlmModelSpec CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AEL.Core.Docling.Gamma.Models.VlmModelSpec();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_overrides", n => { ApiOverrides = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.VlmModelSpec_api_overrides>(global::AEL.Core.Docling.Gamma.Models.VlmModelSpec_api_overrides.CreateFromDiscriminatorValue); } },
                { "default_repo_id", n => { DefaultRepoId = n.GetStringValue(); } },
                { "engine_overrides", n => { EngineOverrides = n.GetObjectValue<global::AEL.Core.Docling.Gamma.Models.VlmModelSpec_engine_overrides>(global::AEL.Core.Docling.Gamma.Models.VlmModelSpec_engine_overrides.CreateFromDiscriminatorValue); } },
                { "max_new_tokens", n => { MaxNewTokens = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "prompt", n => { Prompt = n.GetStringValue(); } },
                { "response_format", n => { ResponseFormat = n.GetEnumValue<global::AEL.Core.Docling.Gamma.Models.ResponseFormat>(); } },
                { "revision", n => { Revision = n.GetStringValue(); } },
                { "stop_strings", n => { StopStrings = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "supported_engines", n => { SupportedEngines = n.GetCollectionOfEnumValues<global::AEL.Core.Docling.Gamma.Models.VlmEngineType>()?.AsList(); } },
                { "trust_remote_code", n => { TrustRemoteCode = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.VlmModelSpec_api_overrides>("api_overrides", ApiOverrides);
            writer.WriteStringValue("default_repo_id", DefaultRepoId);
            writer.WriteObjectValue<global::AEL.Core.Docling.Gamma.Models.VlmModelSpec_engine_overrides>("engine_overrides", EngineOverrides);
            writer.WriteIntValue("max_new_tokens", MaxNewTokens);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("prompt", Prompt);
            writer.WriteEnumValue<global::AEL.Core.Docling.Gamma.Models.ResponseFormat>("response_format", ResponseFormat);
            writer.WriteStringValue("revision", Revision);
            writer.WriteCollectionOfPrimitiveValues<string>("stop_strings", StopStrings);
            writer.WriteCollectionOfEnumValues<global::AEL.Core.Docling.Gamma.Models.VlmEngineType>("supported_engines", SupportedEngines);
            writer.WriteBoolValue("trust_remote_code", TrustRemoteCode);
        }
    }
}
#pragma warning restore CS0618
