// <auto-generated/>
#pragma warning disable CS0618
using AEL.Core.Docling.Gamma.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace AEL.Core.Docling.Gamma.V1.Status.Poll.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\status\poll\{task_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTask_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::AEL.Core.Docling.Gamma.V1.Status.Poll.Item.WithTask_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTask_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/status/poll/{task_id}{?wait*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AEL.Core.Docling.Gamma.V1.Status.Poll.Item.WithTask_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTask_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/status/poll/{task_id}{?wait*}", rawUrl)
        {
        }
        /// <summary>
        /// Task Status Poll
        /// </summary>
        /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.Models.TaskStatusResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::AEL.Core.Docling.Gamma.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::AEL.Core.Docling.Gamma.Models.TaskStatusResponse?> GetAsync(Action<RequestConfiguration<global::AEL.Core.Docling.Gamma.V1.Status.Poll.Item.WithTask_ItemRequestBuilder.WithTask_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::AEL.Core.Docling.Gamma.Models.TaskStatusResponse> GetAsync(Action<RequestConfiguration<global::AEL.Core.Docling.Gamma.V1.Status.Poll.Item.WithTask_ItemRequestBuilder.WithTask_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::AEL.Core.Docling.Gamma.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::AEL.Core.Docling.Gamma.Models.TaskStatusResponse>(requestInfo, global::AEL.Core.Docling.Gamma.Models.TaskStatusResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Task Status Poll
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::AEL.Core.Docling.Gamma.V1.Status.Poll.Item.WithTask_ItemRequestBuilder.WithTask_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::AEL.Core.Docling.Gamma.V1.Status.Poll.Item.WithTask_ItemRequestBuilder.WithTask_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::AEL.Core.Docling.Gamma.V1.Status.Poll.Item.WithTask_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::AEL.Core.Docling.Gamma.V1.Status.Poll.Item.WithTask_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::AEL.Core.Docling.Gamma.V1.Status.Poll.Item.WithTask_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Task Status Poll
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithTask_ItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Number of seconds to wait for a completed status.</summary>
            [QueryParameter("wait")]
            public double? Wait { get; set; }
        }
    }
}
#pragma warning restore CS0618
